### ISSUE TITLE
Misinformation in README.md

### ISSUE THREAD

**Issue by gergelypolonkai** [erinallard/instagram_miner#1]
I have found in the README file that after adding a superuser, you say a `makemigrations` is necessary, but it’s not.

`createsuperuser` just adds a new user to the database with the `staff` and `superuser` flags turned on.

`makemigrations` checks your model files (`models.py` in every app mentioned in the `INSTALLED_APPS` setting) and if that definition differs from your current database layout (ie. what is on the SQL server), it creates a new migration file for it (that you can apply with `manage.py migrate`).

**Comment by erinallard** [comment]
Thank you very much! I am new to Django and really appreciate you taking
the time to write to me. I will update the README now. Have a good day!

Erin

On Mon, May 9, 2016 at 12:18 AM, Gergely Polonkai <notifications@github.com>
wrote:

> I have found in the README file that after adding a superuser, you say a
> makemigrations is necessary, but it’s not.
>
> createsuperuser just adds a new user to the database with the staff and
> superuser flags turned on.
>
> makemigrations checks your model files (models.py in every app mentioned
> in the INSTALLED_APPS setting) and if that definition differs from your
> current database layout (ie. what is on the SQL server), it creates a new
> migration file for it (that you can apply with manage.py migrate).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/erinallard/instagram_miner/issues/1>
>



-- 
Erin Allard
Software Engineer
(510) 228-6085
GitHub <https://github.com/erinallard> | LinkedIn
<http://linkedin.com/in/erinallard1>
